language: nix
  
matrix:
  include:
    - script: nix-shell --packages nixpkgs-lint --run "nixpkgs-lint -f  $TRAVIS_BUILD_DIR/nixos"
    - script: NIX_CONF_DIR="$TRAVIS_BUILD_DIR/nix" nix-build --show-trace "$TRAVIS_BUILD_DIR/nixos"
    - script: ./nixos/make-iso.nix
    - script: ./nixos/make-qemu-vm.nix && ( set -ex; cmdpid=$BASHPID; (sleep 300; kill $cmdpid 2>/dev/null) & ./result/bin/run-vm-vm -nographic && false )

notifications:
    email:
        on_success: never
        on_failure: change
