# Copyright 2017-2018 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
language: nix
sudo: required
services:
  - docker

env:
  global:
    - NIX_PATH="nixpkgs=channel:nixos-18.03:nixpkgs-overlays=$TRAVIS_BUILD_DIR/nix/overlays"

matrix:
  include:
    - before_install: nix-channel --list
      script: nix-build '<nixpkgs>' -A myconfig
      env: NAME="nix-build default.nix -A myconfig"
    - script: docker build -t myconfig --build-arg TERM --build-arg NIX_PATH --rm=true --force-rm=true .
      env: NAME="build myconfig within docker"
    - install: ./nixos/derivations/make-qemu-vm.nix
      script: ./_tests/vmtest.sh ./result/bin/run-myconfig-vm-vm
      env: NAME="vmtest (empty configuration)"
    - install: ./nixos/derivations/make-qemu-vm.nix --arg machine '"minimal"'
      script: ./_tests/vmtest.sh ./result/bin/run-myconfig-vm-vm
      env: NAME="vmtest (minimal configuration)"

# ################################################################################
# ## tests that do not actually test anything (never fail)
#     - script: nix-shell -p nixpkgs-lint --run "nixpkgs-lint -f  ./"
#       env: NAME="nixpkgs-lint"
#
# ################################################################################
# ## tests that are allowed to fail (but succeed on local execution)
#     - before_install: nix-channel --list && nix-env -i stack
#       install: cd xmonad && stack setup && stack build
#       script: cd xmonad && stack test
#       env: NAME="build xmonad with stack"
#     - install: ./nixos/derivations/make-qemu-vm.nix --arg machine '"T470p"'
#       script: ./_tests/vmtest.sh ./result/bin/run-myconfig-vm-vm
#       env: NAME="vmtest (T470p configuration)"
#     - install: ./nixos/derivations/make-qemu-vm.nix
#       script: ./_tests/vmtest.sh ./result/bin/run-myconfig-vm-vm --arg machine '"workstation"'
#       env: NAME="vmtest (workstation configuration)"
#     - script: ./nixos/derivations/make-iso.nix
#       env: NAME="make-iso.nix"
#
# ################################################################################
# ## tests that are not yet implemented
#     # TODO: emacs / spacemacs config test
#     # - install: #somehow setup emacs dotfiles
#     #   script: emacs --batch --eval '(byte-recompile-directory "~/.emacs.d")' && emacs --debug-init -nw --exec "(save-buffers-kill-emacs)"
#     #   env: NAME="test emacs config"
#
#   allow_failures:
# ### dies because of missind Xrandr libraries
#     - before_install: nix-channel --list && nix-env -i stack
#       install: cd xmonad && stack setup && stack build
#       script: cd xmonad && stack test
#       env: NAME="build xmonad with stack"
# ### dies becaus of: out of disk
#     - install: ./nixos/derivations/make-qemu-vm.nix --arg machine '"T470p"'
#       script: ./_tests/vmtest.sh ./result/bin/run-myconfig-vm-vm
#       env: NAME="vmtest (T470p configuration)"
#     - install: ./nixos/derivations/make-qemu-vm.nix
#       script: ./_tests/vmtest.sh ./result/bin/run-myconfig-vm-vm --arg machine '"workstation"'
#       env: NAME="vmtest (workstation configuration)"
# ### dies becaus of: time out
#     - script: ./nixos/derivations/make-iso.nix
#       env: NAME="make-iso.nix"

notifications:
  email:
    on_success: never
    on_failure: change
    # on_failure: always
