language: nix
  
matrix:
  include:
    - script: nix-shell --packages nixpkgs-lint --run "nixpkgs-lint -f  $TRAVIS_BUILD_DIR/nixos/derivations"
    - script: NIX_CONF_DIR="$TRAVIS_BUILD_DIR/nix" nix-build --show-trace "$TRAVIS_BUILD_DIR/nixos/derivations"
    - script: ./nixos/derivations/make-iso.nix
    - script: ./nixos/derivations/make-qemu-vm.nix --arg machine \"mobile\" && ( set -ex; cmdpid=$BASHPID; (sleep 300; kill $cmdpid 2>/dev/null) & ./result/bin/run-vm-vm -nographic && false ) ; [[ $? -eq 143 ]]

notifications:
  email:
    on_success: never
    # on_failure: change
    on_failure: always
